name: License Compliance Scan
on:
  push:
    branches: [main]
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan code for license compliance
        uses: github/super-linter@v5
        with:
          # Disable all linters except scancode
          disabled-linters: "eslint,phpstan,php-codesniffer,phpmd,pylint,rubocop,remark-lint,shellcheck,stylelint,terraform"
          enable-linters: "scancode,golangci-lint"
          # Specify the Scancode and golangci-lint versions to use
          scancode-version: "3.3.0"
          golangci-lint-version: "v1.41.1"
          # Specify the path(s) to scan
          linters: |
            scancode:
              paths: .
            golangci-lint:
              paths: .
              args: ["--timeout", "5m"]
