name: Linting
on:
  push:
    branches: [main]
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Scan code for license compliance
        run: golangci-lint run ./cmd/support/main.go
