name: License Compliance Scan
on:
  push:
    branches: [main]
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.41.1
          export PATH=$PATH:$PWD/golangci-lint-1.41.1/bin/
      - name: Scan code for license compliance
        run: golangci-lint run --disable-all --enable license .
