name: License Compliance Scan
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Scancode
        run: |
          sudo apt-get install -y openjdk-11-jre-headless
          wget -q https://github.com/nexB/scancode-toolkit/releases/download/v3.0.1/scancode-toolkit-3.0.1.tar.bz2
          tar xf scancode-toolkit-3.0.1.tar.bz2
          export PATH=$PATH:"$(pwd)/scancode-toolkit-3.0.1/bin"
      - name: Scan code for license compliance
        run: |
          scancode --license --json --classify --summary --delay 3 --timeout 120 .
